import Head from 'next/head'
import styles from '../styles/Home.module.css'
import { Footer } from '../components/Footer'
import { Main } from '../components/Main'
import { Header } from '../components/Header'
import { useCallback, useEffect, useState } from 'react'



export default function Home() {
  const [count,setCount] = useState(1);
  const [text,setText] = useState("");
  const [isShow,setIsShow] = useState(true);
  const [array,setArray] = useState([]);


  // number
  const handleClick = useCallback((e) => {
    if (count < 10){
      setCount((count) => count + 1);
      console.log(count);
    }
  },[count]);

  // string
  const handleChange = useCallback((e) => {
    if(e.target.value.length > 5){
      alert("5文字以内にしてください");
      return;
    }
    setText(e.target.value.trim());
  }, []);

  // true false
  const handleDisplay = useCallback(() => {
    setIsShow((isShow) => {
      return isShow ? false : true;
      // return !isShow
    });
  }, []);

  const handleAdd = useCallback(() => {
    setArray((prevArray) => {
      if(prevArray.some((item) => item === text)){
        alert("同じ要素が既に存在します。");
        return prevArray;
      }
      const newArray = [...prevArray, text];
      return newArray;
    });
  }, [text]);

  // ページ遷移時の処理
  useEffect(() => {
    document.body.style.backgroundColor = "lightblue";

    return() => {
      document.body.style.backgroundColor = "";
    }
  },[count]);


  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />

        {isShow ? <h1>{count}</h1> : null}
        <button onClick={handleClick}>
          ボタン
        </button>
        <input type="text" value={text} onChange={handleChange} />

        
        <button onClick={handleDisplay}>
          {isShow ? "非表示": "表示"}
        </button>
        <button onClick={handleAdd}>追加</button>
        <ul>
          {array.map((item) => {
            return <li key={item}>{item}</li>
          })}
        </ul>
      <Main title="index" />

      <Footer />
    </div>
  )
}
